name: Spam filter
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Rummelsnuff
        uses: andrewslotin/rummelsnuff@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          pr_num: ${{ github.event.pull_request.number }}
